# Generated by Django 4.0 on 2021-12-14 04:52

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='El curso debe tener mínimo 3 caracteres.'), django.core.validators.MaxLengthValidator(20, message='El curso debe tener máximo 20 caracteres')])),
                ('imagen', models.CharField(blank=True, default='default.jpg', max_length=500)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('creado', models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 4, 52, 31, 145811, tzinfo=utc))),
                ('secciones', models.JSONField(default='{}', encoder=object)),
            ],
        ),
    ]
