# Generated by Django 4.0 on 2021-12-14 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creado',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='secciones',
            field=models.JSONField(default='dict', encoder=object),
        ),
    ]
