# Generated by Django 4.0 on 2021-12-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_alter_curso_creado_alter_curso_secciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='secciones',
            field=models.JSONField(default=dict, encoder=object),
        ),
    ]
