"""
Django settings for Entrenate project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR=Path(__file__).resolve(strict=True).parent.parent
# MEDIA_URL='/Photos/'
# MEDIA_ROOT=os.path.join(BASE_DIR,"Photos")



# print(BASE_DIR) # E:\Desktop\Ingenieria Software I (Proyecto)\Entrenate
# SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))
TEMPLATE_DIRS = [os.path.join(os.path.join(BASE_DIR, 'Entrenate'), 'templates')]
#TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)
# /usr/lib/python2.5/site-packages/projectname/templates/template1.html
# /usr/lib/python2.5/site-packages/projectname/templates/template2.html
# /usr/lib/python2.5/site-packages/projectname/templates/template3.html

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mlalk5rm5d-u8z#!ia24cs3jxy)6akkrof&jkb05xvnpo2))uf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'Entrenate.apps.Usuarios',
    'Entrenate.apps.Cursos',
    'Entrenate.apps.Autenticacion',
    'Entrenate.apps.Foros',
    'Entrenate.apps.Inscripciones'
]

CORS_ORIGIN_ALLOW_ALL = True # Deberiamos tener de hecho un whitelist con las rutas que pueden hacer requests a nuestra API, aqui estamos dando acceso a todo. 0.0.0.0/0

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Entrenate.middlewares.AuthenticationMiddleware',
    'Entrenate.middlewares.AuthorizationMiddleware'
]

ROOT_URLCONF = 'Entrenate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Entrenate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'E-ntrenate',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host':'mongodb+srv://dapstab:kidAmnesia@e-ntrenate.nnlqu.mongodb.net/E-ntrenate?retryWrites=true&w=majority'
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(os.path.join(BASE_DIR, 'Entrenate'), 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = 'smtp.googlemail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "entrenateisw@gmail.com"
EMAIL_HOST_PASSWORD = "cheemsquad123"
#EMAIL_HOST_USER = "dspt1996@gmail.com"
#EMAIL_HOST_PASSWORD = config("UEP")
EMAIL_USE_TLS = True
