# Generated by Django 4.0 on 2021-12-14 03:26

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(8, 'La contraseña necesita ser mayor de 8 caracteres')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 3, 25, 49, 482738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, default='default.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='passwordChangeAt',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='passwordResetExpires',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='passwordResetToken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('es', 'Estudiante'), ('pr', 'Profesor')], default='es', max_length=20),
        ),
    ]
