# Generated by Django 4.0 on 2021-12-14 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuario_contraseña_alter_usuario_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
